- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      vars:
        URL: task.google.com
      ansible.builtin.debug:
        msg: Var URL - {{ URL }}
    - name: Print play level variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
