- name: Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print fruits
      ansible.builtin.debug:
        msg: Fruit name - {{ item }}
      loop:
        - Apple
        - Banana
        - Orange

    - name: Print fruits with quantities
      ansible.builtin.debug:
        msg: Fruit name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - {name: Apple, quantity: 5}
        - {name: Banana, quantity: 10}
        - {name: Orange, quantity: 15}
