- name: Error handling
  hosts: localhost
  connection: local
  tasks:
  - name: Print
    ansible.builtin.shell: cat /etc/passwd | grep demo
    ignore_errors: true
  - name: Print
    ansible.builtin.shell: ls